# Generated by Django 4.2.7 on 2023-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
