# Generated by Django 4.2.7 on 2023-12-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_market', '0002_alter_itemmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemModel',
            new_name='Item',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounts', models.ManyToManyField(to='pay_market.discount')),
                ('items', models.ManyToManyField(to='pay_market.item')),
                ('taxes', models.ManyToManyField(to='pay_market.tax')),
            ],
        ),
    ]
